[package]
name = "dotlock-bin"
version = "0.1.1"
edition = "2024"
description = "Encrypted project-local environment variables manager"
license = "MIT OR Apache-2.0"
repository = "https://github.com/filipe-freitas-dev/dotlock"
readme = "README.md"
keywords = ["cli", "secrets", "env", "encryption"]
categories = ["command-line-utilities"]

[[bin]]
name = "dl"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.102"
argon2 = "0.5.3"
base64 = "0.22.1"
chacha20poly1305 = "0.10.1"
clap = { version = "4.6.1", features = ["derive"] }
colored = "3"
getrandom = "0.4.2"
hkdf = "0.13.0"
inquire = "0.7"
rand_core = "0.10.1"
rsa = { version = "0.9.8", features = ["pem", "sha2", "pkcs5"] }
serde = { version = "1.0.228", features = ["derive"] }
sha2 = "0.11.0"
thiserror = "2.0.18"
tokio = { version = "1.52.2", features = ["full"] }
toml = "1.1.2"
uuid = { version = "1", features = ["v4", "serde"] }
zeroize = "1.8.2"
